testproject/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)

urlpatterns =[
    # url(r'^$',views.home),
    # url(r'^home/$',views.home,name="home"),
    url(r'^login/$',login,{'template_name':'accounts/login.html'},name="login"),
    url(r'^logout/$',logout,{'template_name':'accounts/logout.html'}, name= "logout"),
    url(r'^register/$',views.registerUser, name="registerUser" ), 
    url(r'^profile/$',views.profile, name="profile" ),
    url(r'^profile/(?P<pk>\d+)/$',views.profile, name="profile_with_pk" ),    
    url(r'^profile/edit/$',views.editProfile, name="editProfile" ),
    url(r'^profile/change-password/$',views.changePassword, name="changePassword" ),

    url(r'^reset-password/$',password_reset,{'template_name':'accounts/password-reset.html',
    'post_reset_redirect':'accounts:password_reset_done','email_template_name':'accounts/password_reset_email.html'},
    name="password_reset"),

    url(r'^reset-password/done/$',password_reset_done,{'template_name':'accounts/password_reset_sent.html'},
    name="password_reset_done"),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm,{'post_reset_redirect':'accounts:password_reset_complete',
    'template_name':'accounts/password_reset_confirmation.html'},name="password_reset_confirm"),


    # python -m smtpd -n -c DebuggingServer localhost:1025
    url(r'^reset-password/complete/$',password_reset_complete,{'template_name':'accounts/password_reset_complete.html'},
    name="password_reset_complete"),            
    
]

testproject/home/urls.py
from django.conf.urls import url
from home import views

urlpatterns=[
    url(r'^$',views.HomeView.as_view(),name="home"),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',views.change_friends,name="change_friends"),    

]

testproject/testproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from testproject import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$',views.loginRedirect, name="loginRedirect"),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^home/', include('home.urls', namespace="home"))
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testproject/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import signals

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    city = models.CharField(max_length=50,default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image',blank=True)

    def __str__(self):
        return self.user.username

def createProfile(sender, **kwargs):
    if kwargs["created"]:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


signals.post_save.connect(createProfile,sender=User)

testproject/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    post = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post


class Friend(models.Model):
    users = models.ManyToManyField(User,related_name="friend_set")
    current_user = models.ForeignKey(User,related_name="owner",null=True)

    @classmethod
    def make_friend(cls,current_user,new_friend):
        friend, created = cls.objects.get_or_create(
            current_user = current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls,current_user,new_friend):
        friend, created = cls.objects.get_or_create(
            current_user = current_user
        )
        friend.users.remove(new_friend)

testproject/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegisterationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        )

    
    def save(self, commit=True):
        user = super(RegisterationForm,self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields=(
            'username',
            'first_name',
            'last_name',
            'email',
            'password'
        )
        # exclude=()

    

testproject/home/forms.py
from django import forms
from home import models

class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder':'write a post',
        }
    ))

    class Meta:
        model = models.Post
        fields =  ('post',)

testproject/accounts/views.py
from django.shortcuts import render, HttpResponse, redirect
from accounts.forms import (
    RegisterationForm, 
    EditProfileForm
)
from django.contrib.auth.models import User
# from django.contrib.auth.forms import UserChangeForm
# from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required

# Create your views here.
# there are two type of views class based and function based

def registerUser(request):
    if request.method == "POST":
        form = RegisterationForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("/accounts/login")
    else:
        form = RegisterationForm()

        args = {"form": form}

        return render(request,"accounts/registration.html",args)

# @login_required
def profile(request, pk=None):
    # user = None
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user

    args = {'user':user}
    return render(request,"accounts/profile.html",args)


# @login_required
def editProfile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid:
            form.save()
            return redirect("/accounts/profile")
    
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request,"accounts/edit_profile.html",args)

# @login_required
def changePassword(request):
    if request.method=="POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect("/accounts/profile")

    else:
            form = PasswordChangeForm(user=request.user)
            args = {'form':form}
            return render(request,"accounts/change_password.html",args)

testproject/home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.contrib.auth.models import User

from home import forms
from home import models


class HomeView(TemplateView):
    template_name = "home/home.html"

    def get(self,request):
        form = forms.HomeForm()
        posts = models.Post.objects.all().order_by('-created')
        users = User.objects.exclude(id=request.user.id)
        friend = models.Friend.objects.get(current_user=request.user)

        friends = friend.users.all()


        # print(posts)
        args = {'form':form,'posts':posts,'users':users,'friends':friends}

        return render(request,self.template_name,args)

    
    def post(self,request):
        form = forms.HomeForm(request.POST)
        text = ''
        if form.is_valid():
            
            post = form.save(commit=False)
            post.user = request.user
            post.save()


            text = form.cleaned_data['post']
            # print("text:"+text)
            form = forms.HomeForm()
            return redirect("home:home")
            

        args = {'form':form, 'text':text}
        return render(request,self.template_name,args)


def change_friends(request,operation,pk):
    new_friend = User.objects.get(pk=pk)
    if operation == "add":
        models.Friend.make_friend(request.user,new_friend)
    
    elif operation == "remove":
        models.Friend.lose_friend(request.user,new_friend)
        

    return redirect("home:home")

testproject/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Change Password</title>
    {% endblock %}
</head>
<body>
    {% block body %}

    <div class="container">
            <h1>Change Password</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Submit</button>
            </form>

    </div>

    
    {% endblock %}

</body>
</html>

testproject/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Edit User Profile</title>
    {% endblock %}
</head>
<body>
    {% block body %}

    <div class="container">
            <h1>Edit User Profile</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Submit</button>
            </form>

    </div>

    
    {% endblock %}

</body>
</html>

testproject/accounts/templates/accounts/home.html
{% extends 'base.html' %}
<!DOCTYPE <!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Home Page</title>
    {% endblock %}
</head>
<body>
    {% block body %}

    <h1>Home</h1>

    {% endblock %}

</body>
</html>

testproject/accounts/templates/accounts/login.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Accounts Login</title>
    <!-- {% load static %} -->
    <!-- <link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css"> -->

    {% endblock %}

</head>
<body>
    
    {% block body %}
    <div class="container">
        <h1>Accounts Login</h1>
        <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary btn-lg" type="submit">Login</button>
        </form>
    </div>
    {% endblock %}

</body>
</html>

testproject/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Accounts Login</title>
    {% endblock %}

</head>
<body>
    
    {% block body %}
    <div class="container">
        <h1>Accounts Logout!!</h1>
    </div>
    {% endblock %}

</body>
</html>

testproject/accounts/templates/accounts/password-reset.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Password Reset</title>

    {% endblock %}

</head>
<body>
    
    {% block body %}
    <div class="container">
        <h1>Password Reset</h1>
        <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary btn-lg" type="submit">Reset</button>
        </form>
    </div>
    {% endblock %}

</body>
</html>

testproject/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Password reset complete</title>
    {% endblock %}

</head>
<body>
    
    {% block body %}
    <div class="container">
        <h1>Password reset complete!!</h1>
        <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
            
            If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder. 
        </p>

        <a href="{% url 'accounts:login' %}">Login</a>

    </div>
    {% endblock %}

</body>
</html>

testproject/accounts/templates/accounts/password_reset_confirmation.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Password reset confirmation </title>

    {% endblock %}

</head>
<body>
    
    {% block body %}
    <div class="container">
        <h1>Enter new password</h1>
        <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary btn-lg" type="submit">Change my password</button>
        </form>
    </div>
    {% endblock %}

</body>
</html>

testproject/accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
	
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
 	
{% trans "Thanks for using our site!" %}
	
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
 	
{% endautoescape %}

testproject/accounts/templates/accounts/password_reset_sent.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Password reset sent</title>
    {% endblock %}

</head>
<body>
    
    {% block body %}
    <div class="container">
        <h1>Password reset sent!!</h1>
        <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
            
            If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder. 
        </p>

        <a href="{% url 'accounts:login' %}">Login</a>

    </div>
    {% endblock %}

</body>
</html>

testproject/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>User Profile</title>
    {% endblock %}
</head>
<body>
    {% block body %}

    <div class="container">
            <h1>User Profile</h1>
            <p>
                    <h2>username: {{ user.userprofile }}</h2>
                    <h2>First Name: {{ user.first_name }}</h2>            
                    <h2>Last Name: {{ user.last_name }}</h2>            
                    <h2>Email: {{ user.email }}</h2>            
                    <h2>Description: {{ user.userprofile.description }}</h2>            
                    <h2>phone: {{ user.userprofile.phone }}</h2>            
                    <h2>website: {{ user.userprofile.website }}</h2>
                    {% if user.userprofile.image %}            
                    <img src="{{ user.userprofile.image.url }}" width="200" height="220">
                    {% endif %}
            </p>

    </div>

    
    {% endblock %}

</body>
</html>

testproject/accounts/templates/accounts/registration.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Registration</title>
    {% endblock %}
</head>
<body>
            {% block body %}
            <div class="container">
                <h1>Registration</h1>

                <form   method="post">
                    <div class="form-group">
                            {% csrf_token %}
                            
                            {{ form.as_p }}
                            
                            <button type="submit" >Register</button>
                    </div>
                </form>
            </div>
            {% endblock %}

</body>
</html>