testproject/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)

urlpatterns =[
    # url(r'^$',views.home),
    # url(r'^home/$',views.home,name="home"),
    url(r'^login/$',login,{'template_name':'accounts/login.html'},name="login"),
    url(r'^logout/$',logout,{'template_name':'accounts/logout.html'}, name= "logout"),
    url(r'^register/$',views.registerUser, name="registerUser" ), 
    url(r'^profile/$',views.profile, name="profile" ),
    url(r'^profile/(?P<pk>\d+)/$',views.profile, name="profile_with_pk" ),    
    url(r'^profile/edit/$',views.editProfile, name="editProfile" ),
    url(r'^profile/change-password/$',views.changePassword, name="changePassword" ),

    url(r'^reset-password/$',password_reset,{'template_name':'accounts/password-reset.html',
    'post_reset_redirect':'accounts:password_reset_done','email_template_name':'accounts/password_reset_email.html'},
    name="password_reset"),

    url(r'^reset-password/done/$',password_reset_done,{'template_name':'accounts/password_reset_sent.html'},
    name="password_reset_done"),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm,{'post_reset_redirect':'accounts:password_reset_complete',
    'template_name':'accounts/password_reset_confirmation.html'},name="password_reset_confirm"),


    # python -m smtpd -n -c DebuggingServer localhost:1025
    url(r'^reset-password/complete/$',password_reset_complete,{'template_name':'accounts/password_reset_complete.html'},
    name="password_reset_complete"),            
    
]

testproject/home/urls.py
from django.conf.urls import url
from home import views

urlpatterns=[
    url(r'^$',views.HomeView.as_view(),name="home"),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',views.change_friends,name="change_friends"),    

]

testproject/testproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from testproject import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$',views.loginRedirect, name="loginRedirect"),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^home/', include('home.urls', namespace="home"))
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testproject/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import signals

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    city = models.CharField(max_length=50,default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image',blank=True)

    def __str__(self):
        return self.user.username

def createProfile(sender, **kwargs):
    if kwargs["created"]:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


signals.post_save.connect(createProfile,sender=User)

testproject/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegisterationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        )

    
    def save(self, commit=True):
        user = super(RegisterationForm,self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields=(
            'username',
            'first_name',
            'last_name',
            'email',
            'password'
        )
        # exclude=()

    

testproject/accounts/views.py
from django.shortcuts import render, HttpResponse, redirect
from accounts.forms import (
    RegisterationForm, 
    EditProfileForm
)
from django.contrib.auth.models import User
# from django.contrib.auth.forms import UserChangeForm
# from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required

# Create your views here.
# there are two type of views class based and function based

def registerUser(request):
    if request.method == "POST":
        form = RegisterationForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("/accounts/login")
    else:
        form = RegisterationForm()

        args = {"form": form}

        return render(request,"accounts/registration.html",args)

# @login_required
def profile(request, pk=None):
    # user = None
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user

    args = {'user':user}
    return render(request,"accounts/profile.html",args)


# @login_required
def editProfile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid:
            form.save()
            return redirect("/accounts/profile")
    
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request,"accounts/edit_profile.html",args)

# @login_required
def changePassword(request):
    if request.method=="POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect("/accounts/profile")

    else:
            form = PasswordChangeForm(user=request.user)
            args = {'form':form}
            return render(request,"accounts/change_password.html",args)

testproject/accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block head %}
    <title>Base Page</title>
    {% endblock %}
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
                <a class="navbar-brand" href="{% url 'accounts:login' %}">Alector Lab</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
        
                <div class="collapse navbar-collapse" id="navbarsExample09">

                  {% if user.is_authenticated %}
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:registerUser' %}">Register</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link disabled" href="{% url 'accounts:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link disabled" href="{% url 'accounts:changePassword'   %}">Change Password</a>
                    </li>
                    
                    <li class="nav-item">
                      <a class="nav-link disabled" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                  </ul>
                  {% else %}
                  <ul class="navbar-nav mr-auto">
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home:home'  %}">Home<span class="sr-only">(current)</span></a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:registerUser' %}">Register</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link disabled" href="{% url 'accounts:password_reset' %} ">Reset Password</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                      </li>
                  </ul>

                  {% endif %}


                  <form class="form-inline my-2 my-md-0">
                    <input class="form-control" type="text" placeholder="Search" aria-label="Search">
                  </form>
                </div>
              </nav>
    {% block body %}
    <h1>Base</h1>
    {% endblock %}
    
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>