testproject/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)

urlpatterns =[
    # url(r'^$',views.home),
    # url(r'^home/$',views.home,name="home"),
    url(r'^login/$',login,{'template_name':'accounts/login.html'},name="login"),
    url(r'^logout/$',logout,{'template_name':'accounts/logout.html'}, name= "logout"),
    url(r'^register/$',views.registerUser, name="registerUser" ), 
    url(r'^profile/$',views.profile, name="profile" ),
    url(r'^profile/(?P<pk>\d+)/$',views.profile, name="profile_with_pk" ),    
    url(r'^profile/edit/$',views.editProfile, name="editProfile" ),
    url(r'^profile/change-password/$',views.changePassword, name="changePassword" ),

    url(r'^reset-password/$',password_reset,{'template_name':'accounts/password-reset.html',
    'post_reset_redirect':'accounts:password_reset_done','email_template_name':'accounts/password_reset_email.html'},
    name="password_reset"),

    url(r'^reset-password/done/$',password_reset_done,{'template_name':'accounts/password_reset_sent.html'},
    name="password_reset_done"),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm,{'post_reset_redirect':'accounts:password_reset_complete',
    'template_name':'accounts/password_reset_confirmation.html'},name="password_reset_confirm"),


    # python -m smtpd -n -c DebuggingServer localhost:1025
    url(r'^reset-password/complete/$',password_reset_complete,{'template_name':'accounts/password_reset_complete.html'},
    name="password_reset_complete"),            
    
]

testproject/home/urls.py
from django.conf.urls import url
from home import views

urlpatterns=[
    url(r'^$',views.HomeView.as_view(),name="home"),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',views.change_friends,name="change_friends"),    

]

testproject/testproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from testproject import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$',views.loginRedirect, name="loginRedirect"),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^home/', include('home.urls', namespace="home"))
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testproject/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    post = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post


class Friend(models.Model):
    users = models.ManyToManyField(User,related_name="friend_set")
    current_user = models.ForeignKey(User,related_name="owner",null=True)

    @classmethod
    def make_friend(cls,current_user,new_friend):
        friend, created = cls.objects.get_or_create(
            current_user = current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls,current_user,new_friend):
        friend, created = cls.objects.get_or_create(
            current_user = current_user
        )
        friend.users.remove(new_friend)

testproject/home/forms.py
from django import forms
from home import models

class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder':'write a post',
        }
    ))

    class Meta:
        model = models.Post
        fields =  ('post',)

testproject/home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.contrib.auth.models import User

from home import forms
from home import models


class HomeView(TemplateView):
    template_name = "home/home.html"

    def get(self,request):
        form = forms.HomeForm()
        posts = models.Post.objects.all().order_by('-created')
        users = User.objects.exclude(id=request.user.id)
        friend = models.Friend.objects.get(current_user=request.user)

        friends = friend.users.all()


        # print(posts)
        args = {'form':form,'posts':posts,'users':users,'friends':friends}

        return render(request,self.template_name,args)

    
    def post(self,request):
        form = forms.HomeForm(request.POST)
        text = ''
        if form.is_valid():
            
            post = form.save(commit=False)
            post.user = request.user
            post.save()


            text = form.cleaned_data['post']
            # print("text:"+text)
            form = forms.HomeForm()
            return redirect("home:home")
            

        args = {'form':form, 'text':text}
        return render(request,self.template_name,args)


def change_friends(request,operation,pk):
    new_friend = User.objects.get(pk=pk)
    if operation == "add":
        models.Friend.make_friend(request.user,new_friend)
    
    elif operation == "remove":
        models.Friend.lose_friend(request.user,new_friend)
        

    return redirect("home:home")

testproject/home/templates/home/home.html
{% extends 'base.html' %}

{% block head %}
    <title>Home Page</title>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
                <div class="col-md-8">
                        <h2>Home</h2>
                        <form method="POST">
                                {% csrf_token %}
                                {{ form.post}}
                                <br>
                                <button type="submit" >Submit</button>
                    
                        </form>
                        {% for post in posts %}
                        <h1> {{ post.post }}</h1>
                        <p>Posted by {{ post.user.get_full_name }} on {{post.created}} </p>
                        {% endfor %}
                </div>
                <div class="col-md-4">
                    <h2>Other people</h2>
                    {% for user in users%}
                        {% if user not in friends %}
                        <a href="{% url 'accounts:profile_with_pk' pk=user.pk %}">
                            <h3>{{ user.username }}</h3>
                        </a>
                        
                        <a href="{% url 'home:change_friends' operation='add' pk=user.pk %}">
                            <button type="button" class="btn btn-success">Add Friend</button>
                            </a>
                        {% endif %}
                    {% endfor %}
                    <br>
                    <h2>Friends</h2>
                    {% for friend in friends%}
                        <a href="{% url 'accounts:profile_with_pk' pk=friend.pk %}">
                            <h3>{{ friend.username }}</h3>
                        </a>
                        <a href="{% url 'home:change_friends' operation='remove' pk=friend.pk %}">
                        <button type="button" class="btn btn-secondary">Remove Friend</button>
                        </a>
                        
                    {% endfor %}
                </div>
        </div>
    </div>
{% endblock %}