sitetutorial/books/urls.py
from django.conf.urls import url
from books import views

urlpatterns=[
    # url(r"^search-form/$",views.search_form),
    url(r"^search/$",views.search,name="search"),
    url(r'^custom/filters/$',views.test_custom_filters),
]

sitetutorial/siteapp/urls.py
from django.conf.urls import url
from siteapp import views

urlpatterns = [
    url(r'^order/$',views.order),
    url(r'^test/$',views.test),    

]

sitetutorial/sitetutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from sitetutorial import views
from sitetutorial import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hello/$',views.hello),
    url(r'^meta/$',views.display_meta),
    url(r'^time/$',views.current_datetime),
    url(r'^time/plus/(?P<fhours>\d{1,2})/$',views.future_datetime),

    url(r'^contact/',include([
        url(r'^$',views.contact),
        url(r'^thanks/$',views.contact),
    ])),

    url(r'^test/$',views.test_method),
    url(r'^test/1/$',views.view_1),
    url(r'^test/2/$',views.view_2),
        
    url(r'^siteapp/',include('siteapp.urls',namespace="siteapp")),
    url(r'^books/',include('books.urls',namespace="books")), #try only '^'
]

if settings.DEBUG:
    urlpatterns+=[url(r'^debuginfo/$',views.debug)]

sitetutorial/books/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField(blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ["name"]

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(blank=True, verbose_name="e-mail")

    def __str__(self):
        return self.first_name+" "+self.last_name


class Book(models.Model):
    title = models.CharField(max_length=200)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

sitetutorial/siteapp/models.py
from django.db import models

# Create your models here.

sitetutorial/sitetutorial/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label="Your E-mail")
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not Enough Words!")
        return message

sitetutorial/books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from books import models

# Create your views here.

# def search_form(request):
#     return render(request,"books/search_form.html")


def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append("Please submit search term.")
        elif len(q) >= 20:
            errors.append("Please submit a search term 20 characters or shorter.")
        else:
            book_obj = models.Book.objects.filter(title__icontains=q)
            args = {'books':book_obj,'query':q}
            return render(request,"books/search_results.html",args)
            # q = "Please submit a search term."
            # return HttpResponse(q)
    return render(request,"books/search_form.html",{"errors":errors})


def test_custom_filters(request):
    context = {"var":"MFAISAL"}
    return render(request,"books/custom_tags_filters.html",context)



    
    
    

sitetutorial/siteapp/views.py
from django.shortcuts import render
from django.template import Template, Context
import datetime
from django.http import HttpResponse

# Create your views here.

# Context way of httpResponse
def order(request):
    fp = open("siteapp/templates/siteapp/order.html")
    t = Template(fp.read())
    fp.close()
    c = Context({'person_name': 'John Smith','company': 'Outdoor Equipment',
                 'ship_date': datetime.date(2017, 7, 2),'ordered_warranty': False})
    html = t.render(c)
    
    return HttpResponse(html)

# Argumentative way of httpResponse
# def order(request):
#     t = "siteapp/order.html"
#     c = {'person_name': 'John Smith','company': 'Outdoor Equipment',
#                  'ship_date': datetime.date(2017, 7, 2),'ordered_warranty': False}
    
#     return render(request,t,c)

class SilentAssertionError(Exception):
    silent_variable_failure = True

class Person(object):
    
    def __init__(self, first_name, last_name):
        self.first_name, self.last_name = first_name, last_name

    def get_first_name(self):
        # raise AssertionError("foo")
        raise SilentAssertionError


def test(request):
    t = "siteapp/test.html"
    # person = {'name': 'Sally', 'age': '43'}
    # c = {'person': person}
    # c = {'person': Person('John', 'Smith')}
    # items = ['apples', 'bananas', 'carrots']
    p = Person('John', 'Smith')
    c = {"person": p}
    return render(request,t,c)


    

    

sitetutorial/sitetutorial/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader, RequestContext , Template
from sitetutorial import forms

import datetime
from django.core.mail import send_mail, get_connection




def test_method(request):
    context = {"user":"mfaisal",'message':'<b>'}
    return render(request,"test.html",context)



def custom_proc(request):
    context = {
        'app':'My App',
        'user':request.user,
        'ip_address':request.META['REMOTE_ADDR']
    }
    return context


def view_1(request):

    # t = loader.get_template("test.html")
    # context = RequestContext(
    #     request,
    #     {'message':'I am view 1'},
    #     processors=[custom_proc]
    # )
    # return t.render(context)

    # return render(request, 'test.html',
    # {'message':'I am view 1'},
    # RequestContext(request,processors=[custom_proc])
    # )


    t = loader.get_template("test.html")
    c = RequestContext(
        request,
         {'message':'I am view 1'},
         processors=[custom_proc]
         )
    return t.render(c)

def view_2(request):
    t = loader.get_template("test.html")
    c = RequestContext(
        request,
         {'message':'I am view 2'},
         processors=[custom_proc]
         )
    return t.render(c)


def contact(request):
    thanks_message = ""
    if request.path == "/contact/thanks/":
        thanks_message = "Thanks for your feedback"


    if request.method == "POST":
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            con = get_connection('django.core.mail.backends.console.EmailBackend')
            send_mail(
                cd['subject'],
                cd['message'],
                cd['email'],
                ['imfaisalpk@gmail.com'],
                connection=con
            )
            return HttpResponseRedirect('/contact/thanks')
    else:
        form = forms.ContactForm(
            initial = {'subject': "I love your site!"}
        )
    
    return render(request,"contact_form.html",{"form":form, "message":thanks_message})

def debug(request):
    pass


def hello(request):
    return HttpResponse("Hello Pakistan!")


def display_meta(request):
    # try:
    #     ua = request.META['HTTP_USER_AGENT']
    # except KeyError:
    #     ua = 'unknown'

    # ua = request.META.get("HTTP_USER_AGENT","unknown")
    # return HttpResponse("Your Browser Info: %s" % ua )

    values = request.META
    html = []
    for key in sorted(values):
        html.append("<tr><td>%s</td><td>%s</td></tr>"%(key,values[key]))
    return HttpResponse("<table>%s</table>"%"\n".join(html))


# Old ways of rendering
# def current_datetime(request):
#     now = datetime.datetime.now()
#     t = get_template("current_datetime.html")
#     c = {'current_date': now}
#     html = t.render(c)
#     return HttpResponse(html)

# New way render ways
def current_datetime(request):
    now = datetime.datetime.now()
    args = {'current_date': now}
    return render(request,"current_datetime.html",args)

def future_datetime(request, fhours=1):
    try:
        fhours = int(fhours)
    except ValueError:
        raise Http404()

    ftime = datetime.datetime.now() + datetime.timedelta(hours=fhours)
    args = {'hour_offset': fhours,"next_time":ftime}
    return render(request,"future_datetime.html",args)
    

sitetutorial/books/templates/books/custom_tags_filters.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Custom Tags and Filters</title>
</head>
<body>
    <!-- {% load books_custom_filters %}
    {{var|initial_letter_filter}} -->

    {% load  books_custom_tags %}
    <!-- {% my_tag 123 "abcd" book.title warning=message|lower profile=user.profile %} -->
    
    {% get_current_time "%Y-%m-%d %I:%M %p" as the_time %}
    <p>The time is {{ the_time }}.</p>

</body>
</html>

sitetutorial/books/templates/books/search_form.html
<html>
    <head>
        <title>Search</title>
    </head>
    <body>
        {% comment %} {% if errors %}
            <p style="color:red">{{errors.error}}</p>        
        {% endif %} {% endcomment %}
        <ul>
                {% for error in  errors %}
                    <li>
                        {{error}}
                    </li>
                
                 {% endfor %}

        </ul>
        

        <form action="{% url 'books:search' %}" method="get">
            {% comment %} {% csrf_token %} {% endcomment %}
            <input type="text" name="q">
            <input type="submit" value="Search">
        </form>
    </body>
</html>

sitetutorial/books/templates/books/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Search Results</title>
</head>
<body>
        <p>You searched for: <strong>{{ query }}</strong></p>
        {% if books %}
            <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
            <ul>
                {% for book in books  %}
                    <li>{{ book.title }}</li>
                    <li>{{ book.publisher }}</li>
                    <li>{{ book.publication_date }}</li>
                {% endfor %}
            </ul>
        
        {% else %}
            <p>No books matched the search term.</p>
        {% endif %}
    
</body>
</html>

sitetutorial/siteapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Base</title>
</head>
<body>
    <h1>Base</h1>
    
</body>
</html>

sitetutorial/siteapp/templates/siteapp/order.html
<html>
    <head>
        <title>Ordering notice</title>
    </head>
    <body>
        <h1>Ordering notice</h1>
        <p>Dear {{ person_name }},</p>
        <p>Thanks for placing an order from {{ company }}. It's scheduled to ship on {{ ship_date|date:"F j, Y" }}.</p>
        <p>Here are the items you've ordered:</p>
        <ul>
            {% for item in item_list %}
            <li>{{ item }}</li>{% endfor %}
        </ul>
        {% if ordered_warranty %}
        <p>Your warranty information will be included in the packaging.</p>
        {% else %}
        <p>
            You didn't order a warranty, so you're on your own when the products inevitably stop working.
        </p>
        {% endif %}
        <p>Sincerely,<br />{{ company }}</p>
    </body>
    </html>

sitetutorial/siteapp/templates/siteapp/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Test</title>
</head>
<body>
    <h1>Test</h1>
    <p>
        {% comment "Just Testing" %} {{ person.name }} is {{ person.age }} years old. {% endcomment %}
        {% comment %} Hello, {{ person.first_name.upper }} {{ person.last_name.isdigit }}. {% endcomment %}
        {% comment %} Item 0 is {{ items.0 }}. {% endcomment %}

        {# {% if not true %} #}

        My name is {{ person.second_name }}
    </p>
    
</body>
</html>

sitetutorial/sitetutorial/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        
        {% endblock %}
    </title>
    {% block head %}
    
    {% endblock  %}
</head>
<body>
    {% block body %}
    
    {% endblock  %}
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

sitetutorial/sitetutorial/templates/contact_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <style type="text/css">
        ul.errorlist {
            margin: 0;
            padding: 0;
        }
        .errorlist li {
            background-color: red;
            color: white;
            display: block;
            font-size: 1.2em;
            margin: 0 0 3px;
            padding: 4px 5px;
        }
    </style>
    <title>Contact</title>

</head>
<body>
    {% if message %}
    <p style="color:green">{{message}}</p>
    {% else %}
        {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
        {% endif %}
        <form action="" method="POST">

                <div class="field">
                        {{ form.subject.errors }}
                        <label for="id_subject">Subject:</label>
                        {{ form.subject }}
                    </div>
                    <div class="field">
                        {{ form.email.errors }}
                        <label for="id_email">Your e-mail address:</label>
                        {{ form.email }}
                    </div>
                    <div class="field">
                        {{ form.message.errors }}
                        <label for="id_message">Message:</label>
                        {{ form.message }}
                    </div>

            {% csrf_token %}
            {% comment %} {{ form.as_p }} {% endcomment %}
            <button type="submit">submit</button>
        </form>
    {% endif %}
    
    
</body>
</html>

sitetutorial/sitetutorial/templates/current_datetime.html
{% extends "base.html" %}
{% block title %}
    Current Date time
{% endblock %}

{% block body %}

{% include "datetime.html" %}

{% endblock  %}

sitetutorial/sitetutorial/templates/datetime.html
<p>
    It is now {{ current_date }}.
</p>

sitetutorial/sitetutorial/templates/future_datetime.html
{% extends "base.html" %}
{% block title %}Future time{% endblock %}
{% block body %}
<p>
    In {{ hour_offset }} hour(s), it will be {{ next_time }}.
</p>
{% endblock %}

sitetutorial/sitetutorial/templates/test.html
{% extends "base.html" %}

{% block title %}
    Test Page
{% endblock  %}
{% block body %}
    {{app}}
    {{user|safe}}
    {{ip_address}}

    {% autoescape off  %}
    {{message}}
    {% endautoescape  %}
{% endblock  %}